### PR TITLE
Fix #319

### LINKED ISSUE #319: client/transport/state.rs: Private types in public interface errors
These appear to have been introduced in #317:

```
   Compiling opcua v0.13.0 (https://github.com/locka99/opcua.git?branch=master#eab4caab)
error[E0446]: crate-private type `OutgoingMessage` in public interface
  --> /home/user/.cargo/git/checkouts/opcua-49af4c4898b3317f/eab4caa/lib/src/client/transport/state.rs:23:1
   |
23 | pub type RequestSend = tokio::sync::mpsc::Sender<OutgoingMessage>;
   | ^^^^^^^^^^^^^^^^^^^^ can't leak crate-private type
   |
  ::: /home/user/.cargo/git/checkouts/opcua-49af4c4898b3317f/eab4caa/lib/src/client/transport/core.rs:53:1
   |
53 | pub(crate) struct OutgoingMessage {
   | --------------------------------- `OutgoingMessage` declared as crate-private

error[E0446]: restricted type `client::transport::state::Request` in public interface
   --> /home/user/.cargo/git/checkouts/opcua-49af4c4898b3317f/eab4caa/lib/src/client/transport/state.rs:115:5
    |
42  |   pub(super) struct Request {
    |   ------------------------- `client::transport::state::Request` declared as restricted
...
115 | /     pub(crate) fn begin_issue_or_renew_secure_channel(
116 | |         &self,
117 | |         request_type: SecurityTokenRequestType,
118 | |         timeout: Duration,
119 | |         sender: RequestSend,
120 | |     ) -> Request {
    | |________________^ can't leak restricted type

For more information about this error, try `rustc --explain E0446`.
error: could not compile `opcua` (lib) due to 2 previous errors
```

CC: @einarmo

### PR DESCRIPTION
**Pull request by einarmo**
I can't actually reproduce this, but the error in the linked issue is fairly clear, this should fix it.

### CODE REVIEW

**Comment by jpds** [comment]
Can confirm that this fixes the compilation on 1.73 for me. :+1:

**Comment by locka99** [comment]
Landed, thanks
